/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[1];
new PlayerText:PlayerTD[MAX_PLAYERS][9];

//Textdraws
PublicTD[0] = TextDrawCreate(296.000000, 188.500000, "LD_POOL:ball");
TextDrawFont(PublicTD[0], 4);
TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[0], 50.000000, 60.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 1);
TextDrawColor(PublicTD[0], 255);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);


//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 314.000000, 255.000000, "boot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.129167, 0.800000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 329.000000, 16.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 1);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 350.000000, 212.000000, "Door (FR)");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.129167, 0.800000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 369.000000, 15.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -65281);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 1);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 339.000000, 185.000000, "lights");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.129167, 0.800000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 358.500000, 15.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1962934017);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 1);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 311.000000, 172.000000, "bonnet");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.129167, 0.800000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 331.500000, 15.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 1433087999);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 1);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 308.000000, 211.000000, "engine");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.191666, 1.049998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 339.000000, 31.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 9109759);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], -16776961);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 1);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 290.000000, 185.000000, "Lock");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.129167, 0.800000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 306.000000, 12.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 1);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 339.000000, 240.000000, "Door (BR)");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.129167, 0.800000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 353.500000, 15.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -65281);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 1);

PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 290.000000, 240.000000, "Door (BL)");
PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.129167, 0.800000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 303.500000, 15.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -65281);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 1);

PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 281.000000, 212.000000, "Door (FL)");
PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.129167, 0.800000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 295.000000, 16.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -65281);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 1);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
