/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/
#include <YSI_Coding\y_hooks>

new Text:aDvTextDraw[3];

hook OnGameModeInit()
{
	aDvTextDraw[0] = TextDrawCreate(6.000000, 269.000000, "_");
	TextDrawFont(aDvTextDraw[0], 1);
	TextDrawLetterSize(aDvTextDraw[0], 0.600000, 2.749999);
	TextDrawTextSize(aDvTextDraw[0], 138.500000, 21.500000);
	TextDrawSetOutline(aDvTextDraw[0], 1);
	TextDrawSetShadow(aDvTextDraw[0], 0);
	TextDrawAlignment(aDvTextDraw[0], 1);
	TextDrawColor(aDvTextDraw[0], -1);
	TextDrawBackgroundColor(aDvTextDraw[0], 255);
	TextDrawBoxColor(aDvTextDraw[0], 852308603);
	TextDrawUseBox(aDvTextDraw[0], 1);
	TextDrawSetProportional(aDvTextDraw[0], 1);
	TextDrawSetSelectable(aDvTextDraw[0], 0);

	aDvTextDraw[1] = TextDrawCreate(7.000000, 270.000000, "Продам гараж. Отличное состояние. Возможен торг");
	TextDrawFont(aDvTextDraw[1], 1);
	TextDrawLetterSize(aDvTextDraw[1], 0.154167, 0.700000);
	TextDrawTextSize(aDvTextDraw[1], 137.000000, 18.500000);
	TextDrawSetOutline(aDvTextDraw[1], 0);
	TextDrawSetShadow(aDvTextDraw[1], 0);
	TextDrawAlignment(aDvTextDraw[1], 1);
	TextDrawColor(aDvTextDraw[1], -1);
	TextDrawBackgroundColor(aDvTextDraw[1], 255);
	TextDrawBoxColor(aDvTextDraw[1], 50);
	TextDrawUseBox(aDvTextDraw[1], 1);
	TextDrawSetProportional(aDvTextDraw[1], 1);
	TextDrawSetSelectable(aDvTextDraw[1], 0);

	aDvTextDraw[2] = TextDrawCreate(7.000000, 287.000000, "Отправитель:");
	TextDrawFont(aDvTextDraw[2], 1);
	TextDrawLetterSize(aDvTextDraw[2], 0.116667, 0.650000);
	TextDrawTextSize(aDvTextDraw[2], 137.000000, 18.500000);
	TextDrawSetOutline(aDvTextDraw[2], 0);
	TextDrawSetShadow(aDvTextDraw[2], 0);
	TextDrawAlignment(aDvTextDraw[2], 1);
	TextDrawColor(aDvTextDraw[2], -1);
	TextDrawBackgroundColor(aDvTextDraw[2], 255);
	TextDrawBoxColor(aDvTextDraw[2], 50);
	TextDrawUseBox(aDvTextDraw[2], 1);
	TextDrawSetProportional(aDvTextDraw[2], 1);
	TextDrawSetSelectable(aDvTextDraw[2], 0);

	return 1;
}

hook GameModeExit()
{
	TextDrawDestroy(aDvTextDraw[0]);
	TextDrawDestroy(aDvTextDraw[1]);
	TextDrawDestroy(aDvTextDraw[2]);
	return 1;
}

/*public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, aDvTextDraw[0]);
		TextDrawShowForPlayer(playerid, aDvTextDraw[1]);
		TextDrawShowForPlayer(playerid, aDvTextDraw[2]);
		return 1;
	}
	return 0;
}
*/